services:
  web:
    build: .
    container_name: fastapi_app_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    command: [ "sh", "-c", "while true; do sleep 1000; done" ]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_dev123@db:5432/disclosure_dev_db
      - EDGAR_IDENTITY=${EDGAR_IDENTITY}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres_db_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_dev123
      - POSTGRES_DB=disclosure_dev_db
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: