"""add fiscal_year_end on companies and add revenue on finances

Revision ID: 2b8500df388e
Revises: be8784a8603d
Create Date: 2026-07-03 11:57:37.452243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8500df388e'
down_revision: Union[str, None] = 'be8784a8603d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 우선 nullable=True로 컬럼을 추가합니다.
    op.add_column('companies', sa.Column('fiscal_year_end', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=True))
    
    # 2. 기존에 존재하던 행들의 fiscal_year_end 값을 기본값('Q4')으로 채워줍니다.
    op.execute("UPDATE companies SET fiscal_year_end = 'Q4' WHERE fiscal_year_end IS NULL")
    
    # 3. 데이터가 모두 채워졌으므로 이제 NOT NULL 제약조건을 적용합니다.
    op.alter_column('companies', 'fiscal_year_end', nullable=False)
    
    op.add_column('finances', sa.Column('revenue', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finances', 'revenue')
    op.drop_column('companies', 'fiscal_year_end')
    # ### end Alembic commands ###
