"""inital table creating

Revision ID: 962ba7a3e19c
Revises: 
Create Date: 2026-06-21 13:13:50.241618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '962ba7a3e19c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('discount_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_free_rate', sa.Float(), nullable=False),
    sa.Column('average_market_return', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rates_id'), 'discount_rates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PAID', name='tier'), nullable=False),
    sa.Column('role', sa.Enum('ROLE_USER', 'ROLE_ADMIN', name='role'), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'NAVER', name='authprovider'), nullable=False),
    sa.Column('monthly_slot_switch_count', sa.Integer(), nullable=False),
    sa.Column('paid_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_payment_day', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termsVersion', sa.String(length=50), nullable=False),
    sa.Column('terms_of_service', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('marketing_and_alerts', sa.Boolean(), nullable=False),
    sa.Column('required_terms_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=50), nullable=False),
    sa.Column('form_type', sa.Enum('REGULAR_10_K', 'REGULAR_10_Q', 'AMENDMENT_10_K_A', 'AMENDMENT_10_Q_A', name='formtype'), nullable=False),
    sa.Column('filing_date', sa.String(length=10), nullable=False),
    sa.Column('primary_document', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=False),
    sa.Column('analysis_status', sa.Enum('NOT_ANALYZED', 'ANALYZING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amends_filing_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amends_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_id'), 'filings', ['id'], unique=False)
    op.create_table('user_valuation_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='unique_user_company_valuation_scenario')
    )
    op.create_index(op.f('ix_user_valuation_scenarios_id'), 'user_valuation_scenarios', ['id'], unique=False)
    op.create_table('user_watchlist_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_alarm_enable', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='unique_user_company_watchlist_slot')
    )
    op.create_index('index_watchlist_user_id', 'user_watchlist_slots', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_slots_id'), 'user_watchlist_slots', ['id'], unique=False)
    op.create_table('dcfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.Enum('FCFE_GROWTH_RATE', 'CAPEX_TO_REVENUE', 'NET_BORROWING_RATE', name='dcfmetric'), nullable=False),
    sa.Column('median_value', sa.Float(), nullable=False),
    sa.Column('median_ci_lower', sa.Float(), nullable=False),
    sa.Column('median_ci_upper', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('bootstrap_replications', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'metric_name', name='unique_dcf_metric')
    )
    op.create_index(op.f('ix_dcfs_id'), 'dcfs', ['id'], unique=False)
    op.create_table('filing_view_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filing_id', name='unique_user_filing_view_history')
    )
    op.create_index(op.f('ix_filing_view_histories_id'), 'filing_view_histories', ['id'], unique=False)
    op.create_table('finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocf', sa.BigInteger(), nullable=False),
    sa.Column('capex', sa.BigInteger(), nullable=False),
    sa.Column('net_borrowing', sa.BigInteger(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=False),
    sa.Column('diluted_shares_outstanding', sa.BigInteger(), nullable=False),
    sa.Column('basic_shares_outstanding', sa.BigInteger(), nullable=False),
    sa.Column('raw_finances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id')
    )
    op.create_index(op.f('ix_finances_id'), 'finances', ['id'], unique=False)
    op.create_table('periodic_filing_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('item', sa.Enum('ITEM_1A', 'ITEM_7', 'ITEM_8', name='filingitem'), nullable=False),
    sa.Column('difference', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('KOR', 'ENG', name='language'), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodic_filing_analyses_id'), 'periodic_filing_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodic_filing_analyses_id'), table_name='periodic_filing_analyses')
    op.drop_table('periodic_filing_analyses')
    op.drop_index(op.f('ix_finances_id'), table_name='finances')
    op.drop_table('finances')
    op.drop_index(op.f('ix_filing_view_histories_id'), table_name='filing_view_histories')
    op.drop_table('filing_view_histories')
    op.drop_index(op.f('ix_dcfs_id'), table_name='dcfs')
    op.drop_table('dcfs')
    op.drop_index(op.f('ix_user_watchlist_slots_id'), table_name='user_watchlist_slots')
    op.drop_index('index_watchlist_user_id', table_name='user_watchlist_slots')
    op.drop_table('user_watchlist_slots')
    op.drop_index(op.f('ix_user_valuation_scenarios_id'), table_name='user_valuation_scenarios')
    op.drop_table('user_valuation_scenarios')
    op.drop_index(op.f('ix_filings_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_discount_rates_id'), table_name='discount_rates')
    op.drop_table('discount_rates')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
