"""fix_foreign_key_ondelete_typo

Revision ID: b9273bfa3b5f
Revises: 73452cd74643
Create Date: 2026-06-24 05:19:21.854231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9273bfa3b5f'
down_revision: Union[str, None] = '73452cd74643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_cik_key', 'companies', type_='unique')
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.drop_constraint('dcfs_filing_id_fkey', 'dcfs', type_='foreignkey')
    op.create_foreign_key(None, 'dcfs', 'filings', ['filing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('filing_view_histories_user_id_fkey', 'filing_view_histories', type_='foreignkey')
    op.drop_constraint('filing_view_histories_filing_id_fkey', 'filing_view_histories', type_='foreignkey')
    op.create_foreign_key(None, 'filing_view_histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'filing_view_histories', 'filings', ['filing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('filings_amends_filing_id_fkey', 'filings', type_='foreignkey')
    op.drop_constraint('filings_company_id_fkey', 'filings', type_='foreignkey')
    op.create_foreign_key(None, 'filings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'filings', 'filings', ['amends_filing_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('finances_filing_id_fkey', 'finances', type_='foreignkey')
    op.create_foreign_key(None, 'finances', 'filings', ['filing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('periodic_filing_analyses_filing_id_fkey', 'periodic_filing_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'periodic_filing_analyses', 'filings', ['filing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_valuation_scenarios_user_id_fkey', 'user_valuation_scenarios', type_='foreignkey')
    op.drop_constraint('user_valuation_scenarios_company_id_fkey', 'user_valuation_scenarios', type_='foreignkey')
    op.create_foreign_key(None, 'user_valuation_scenarios', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_valuation_scenarios', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_watchlist_slots_company_id_fkey', 'user_watchlist_slots', type_='foreignkey')
    op.drop_constraint('user_watchlist_slots_user_id_fkey', 'user_watchlist_slots', type_='foreignkey')
    op.create_foreign_key(None, 'user_watchlist_slots', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_watchlist_slots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_watchlist_slots', type_='foreignkey')
    op.drop_constraint(None, 'user_watchlist_slots', type_='foreignkey')
    op.create_foreign_key('user_watchlist_slots_user_id_fkey', 'user_watchlist_slots', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_watchlist_slots_company_id_fkey', 'user_watchlist_slots', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'user_valuation_scenarios', type_='foreignkey')
    op.drop_constraint(None, 'user_valuation_scenarios', type_='foreignkey')
    op.create_foreign_key('user_valuation_scenarios_company_id_fkey', 'user_valuation_scenarios', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('user_valuation_scenarios_user_id_fkey', 'user_valuation_scenarios', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'periodic_filing_analyses', type_='foreignkey')
    op.create_foreign_key('periodic_filing_analyses_filing_id_fkey', 'periodic_filing_analyses', 'filings', ['filing_id'], ['id'])
    op.drop_constraint(None, 'finances', type_='foreignkey')
    op.create_foreign_key('finances_filing_id_fkey', 'finances', 'filings', ['filing_id'], ['id'])
    op.drop_constraint(None, 'filings', type_='foreignkey')
    op.drop_constraint(None, 'filings', type_='foreignkey')
    op.create_foreign_key('filings_company_id_fkey', 'filings', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('filings_amends_filing_id_fkey', 'filings', 'filings', ['amends_filing_id'], ['id'])
    op.drop_constraint(None, 'filing_view_histories', type_='foreignkey')
    op.drop_constraint(None, 'filing_view_histories', type_='foreignkey')
    op.create_foreign_key('filing_view_histories_filing_id_fkey', 'filing_view_histories', 'filings', ['filing_id'], ['id'])
    op.create_foreign_key('filing_view_histories_user_id_fkey', 'filing_view_histories', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'dcfs', type_='foreignkey')
    op.create_foreign_key('dcfs_filing_id_fkey', 'dcfs', 'filings', ['filing_id'], ['id'])
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.create_unique_constraint('companies_cik_key', 'companies', ['cik'])
    # ### end Alembic commands ###
