"""Finance table Type,Nullable modified

Revision ID: be8784a8603d
Revises: b9273bfa3b5f
Create Date: 2026-06-28 14:21:06.408449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be8784a8603d'
down_revision: Union[str, None] = 'b9273bfa3b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finances', 'stock_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               nullable=True)
    op.alter_column('finances', 'diluted_shares_outstanding',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('finances', 'basic_shares_outstanding',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('finances', 'raw_finances',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finances', 'raw_finances',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('finances', 'basic_shares_outstanding',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('finances', 'diluted_shares_outstanding',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('finances', 'stock_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
